### ISSUE TITLE
Xamarin.iOS crash in AdobeMarketingMobile

### ISSUE THREAD

**Issue by SalaPaolo** [adobe/xamarin-acpcore#28] opened 2021-11-15 10:45 UTC
I'm working with a Xamarin app that uses the acpcore library installed as a Nuget (version 1.0.0).
Looking at the crashes through XCode I see different logs related to AdobeMarketingMobile class.
I open this ticket because what I see it's something very similar to this issue (https://github.com/Adobe-Marketing-Cloud/acp-sdks/issues/184) that was open on the official library, so I thought that maybe the problem it's the same.
At the moment there is not a specific way to reproduce the crash, this appear to be something random.

### Expected Behaviour
No crash

### Actual Behaviour
Random crashes

#### Platform and Version
IPhone X - iOS 15.0.2

#### Logs taken while reproducing problem
[AdobeCrash.txt](https://github.com/adobe/xamarin-acpcore/files/7537975/AdobeCrash.txt)

**Comment by rymorale** [comment] 2021-11-15 16:51
Hi @SalaPaolo, the issue you referenced was resolved in an earlier ACPCore release and the changes are present in the binary used for the Xamarin ACPCore wrapper. Could we get more information regarding the crash? 
1. Does the crash occur every time the app is run? 
2. I know you mention it occurs randomly, but does it occur more often at different stages of the app lifecycle (for example during app startup or when the app is being put in the background)? 
3. Is the crash occurring on a simulator or physical device?

Thanks,
Ryan

**Comment by rymorale** [comment] 2021-11-16 16:47
Thanks for the additional info @SalaPaolo. I'll open an issue internally to track this and will reply here if we have any updates.

**Comment by rymorale** [comment] 2021-11-24 00:15
Hi @SalaPaolo, would you be able to give more information regarding the analytics usage in your app?

**Comment by SalaPaolo** [comment] 2021-11-30 13:27
Hi @rymorale, 
basically what we are doing it's that we configure ACPCore in the application's AppDelegate like this in FinishedLaunching method

`            ACPCore.SetWrapperType(ACPMobileWrapperType.Xamarin);
#if __PROD__
            App.AnalyticsProd = true;
#else
            ACPCore.LogLevel = ACPMobileLogLevel.Verbose;
#endif
            // register SDK extensions
            ACPIdentity.RegisterExtension();
            ACPLifecycle.RegisterExtension();
            ACPSignal.RegisterExtension();
            ACPAnalytics.RegisterExtension();

            // start core
            ACPCore.Start(startCallback);
            AnalyticsManager.TrackActionDelegate = (AdobeAnalytics.Action action, ContextData contextData) =>
            {
                ACPCore.TrackAction(action.Name, contextData.GetDictionary());
            };

            AnalyticsManager.TrackStateDelegate = (AdobeAnalytics.State state, ContextData contextData) =>
            {
                ACPCore.TrackState(state.Name, contextData.GetDictionary());
            };
`
where startCallBack method it's this 

`private void startCallback()
        {
#if __PROD__
            ACPCore.ConfigureWithAppID(App.appID_Prod);
#else
            ACPCore.ConfigureWithAppID(App.appID_Test);
#endif`

Everything seems to work fine, but the point it's that in our XCode crashes we find several crashes as the one I previously attached.

**Comment by rymorale** [comment] 2021-12-02 06:11
Hi @SalaPaolo, we've been unable to reproduce the crash issue so far. Could we get more info from your end regarding the crash to help narrow down the cause? 
- Is it occurring on iOS15 only or do you see it across different iOS versions?
- Is it occurring with production builds only or reproducible on debug builds as well?
- Can we get the build settings and minimum OS target used?
Additionally, it would be very helpful if you could provide a sample project which mirrors your production app if possible. Multiple logs of the crash would also be very useful to determine a pattern in the crashes.

Thanks again,
Ryan

**Comment by rymorale** [comment] 2021-12-18 00:52
Closing this ticket as we haven't gotten a response in some time. We can re-open in the future if needed.

**Closed by rymorale** 2021-12-18 00:52 UTC
